<?php
/**
 * OmnimessageApi
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Omnichannel API
 *
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Messente\Omnichannel\Api;

use \Messente\Omnichannel\ApiClient;
use \Messente\Omnichannel\ApiException;
use \Messente\Omnichannel\Configuration;
use \Messente\Omnichannel\ObjectSerializer;

/**
 * OmnimessageApi Class Doc Comment
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OmnimessageApi
{
    /**
     * API Client
     *
     * @var \Messente\Omnichannel\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Messente\Omnichannel\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Messente\Omnichannel\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Messente\Omnichannel\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Messente\Omnichannel\ApiClient $apiClient set the API client
     *
     * @return OmnimessageApi
     */
    public function setApiClient(\Messente\Omnichannel\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation sendOmnimessage
     *
     * Sends an Omnimessage
     *
     * @param \Messente\Omnichannel\Model\Omnimessage $body Omnimessage to be sent (required)
     * @throws \Messente\Omnichannel\ApiException on non-2xx response
     * @return \Messente\Omnichannel\Model\OmniMessageCreateSuccessResponse
     */
    public function sendOmnimessage($body)
    {
        list($response) = $this->sendOmnimessageWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation sendOmnimessageWithHttpInfo
     *
     * Sends an Omnimessage
     *
     * @param \Messente\Omnichannel\Model\Omnimessage $body Omnimessage to be sent (required)
     * @throws \Messente\Omnichannel\ApiException on non-2xx response
     * @return array of \Messente\Omnichannel\Model\OmniMessageCreateSuccessResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendOmnimessageWithHttpInfo($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling sendOmnimessage');
        }
        // parse inputs
        $resourcePath = "/omnimessage";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Messente\Omnichannel\Model\OmniMessageCreateSuccessResponse',
                '/omnimessage'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Messente\Omnichannel\Model\OmniMessageCreateSuccessResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Messente\Omnichannel\Model\OmniMessageCreateSuccessResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Messente\Omnichannel\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
