<?php
/**
 * Status
 *
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Omnichannel API
 *
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Messente\Omnichannel\Model;

/**
 * Status Class Doc Comment
 *
 * @category    Class
 * @description The human-readable equivalent for this field is contained in \&quot;error\&quot;. This value is *null* if the message is still being processed.
 * @package     Messente\Omnichannel
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Status
{
    /**
     * Possible values of this enum
     */
    const ACK = 'ACK';
    const DELIVRD = 'DELIVRD';
    const UNDELIV = 'UNDELIV';
    const FAILED = 'FAILED';
    const UNKNOWN = 'UNKNOWN';
    const ACCEPTD = 'ACCEPTD';
    const REJECTD = 'REJECTD';
    const DELETED = 'DELETED';
    const EXPIRED = 'EXPIRED';
    const NACK = 'NACK';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACK,
            self::DELIVRD,
            self::UNDELIV,
            self::FAILED,
            self::UNKNOWN,
            self::ACCEPTD,
            self::REJECTD,
            self::DELETED,
            self::EXPIRED,
            self::NACK,
        ];
    }
}


