<?php
/**
 * ErrTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Omnichannel API
 *
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Messente\Omnichannel;

/**
 * ErrTest Class Doc Comment
 *
 * @category    Class */
// * @description Machine-readable error code, &#x60;null&#x60; when the message has not been processed yet * 0 - No error * 1 - General fatal error * 2 - Sending message expired * 3 - Invalid number * 4 - Error crediting account * 5 - Invalid number format * 6 - Too many identical messages * 7 - Sender name not allowed * 8 - Sender name not allowed * 9 - Operator blacklisted * 10 - Unroutable * 999 - General temporary error
/**
 * @package     Messente\Omnichannel
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Err"
     */
    public function testErr()
    {
    }
}
