<?php
/**
 * OmnimessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Omnichannel API
 *
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@messente.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OmnimessageTest Class Doc Comment
 *
 * @category    Class */
// * @description Omnimessage
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OmnimessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Omnimessage"
     */
    public function testOmnimessage()
    {
    }

    /**
     * Test attribute "scenarios"
     */
    public function testPropertyScenarios()
    {
    }

    /**
     * Test attribute "viber"
     */
    public function testPropertyViber()
    {
    }

    /**
     * Test attribute "sms"
     */
    public function testPropertySms()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "drl_url"
     */
    public function testPropertyDrlUrl()
    {
    }

    /**
     * Test attribute "time_to_send"
     */
    public function testPropertyTimeToSend()
    {
    }
}
