<?php
/**
 * TextStoreTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnichannel API
 *
 * Messente's API which allows sending messages via various channels with fallback options.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: messente@messente.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Messente\Omnichannel;

use PHPUnit\Framework\TestCase;

/**
 * TextStoreTest Class Doc Comment
 *
 * @category    Class
 * @description Whether to store message content as is (plaintext), as a hashed value (sha256) or not at all (nostore).
 * @package     Messente\Omnichannel
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TextStoreTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TextStore"
     */
    public function testTextStore()
    {
    }
}
