<?php
/**
 * DeliveryReportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Omnichannel API
 *
 * This is the beta version of Omnichannel API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Messente\Omnichannel;

use \Messente\Omnichannel\Configuration;
use \Messente\Omnichannel\ApiClient;
use \Messente\Omnichannel\ApiException;
use \Messente\Omnichannel\ObjectSerializer;

/**
 * DeliveryReportApiTest Class Doc Comment
 *
 * @category Class
 * @package  Messente\Omnichannel
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeliveryReportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for omnimessageOmnimessageIdStatusGet
     *
     * .
     *
     */
    public function testOmnimessageOmnimessageIdStatusGet()
    {
    }
}
